CREATE TABLE "GCG_5660_BIN_PARTS"(
 "PART" CHAR(20) NOT NULL,
 "DESCRIPTION" CHAR(30),
 "BIN" CHAR(10) NOT NULL,
 "QTY" NUMERIC(12,4) NOT NULL,
 "JSS" CHAR(15),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQUENCE" CHAR(6),
 "MOBILE_USER" CHAR(30),
 "DATE_IN" DATE,
 "TIME_IN" TIME );